### ISSUE TITLE
Consider supporting the  Permissions-Policy header

### ISSUE THREAD

**Issue by Lawouach** [tmotagam/Secweb#1]
Hey there,

I am using your awesome project for some of my apps and I was using securityheaders.io to check my score. Ity mentions I am missing  the [Permissions-Policy](https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/) header. Do you think this falls under the remit of your project?

**Comment by tmotagam** [comment]
Hello 
I am working on it will update it soon

**Comment by tmotagam** [comment]
I have added Permissions Policy header into the dev version only
