### ISSUE TITLE
No permission to open a PR

### ISSUE THREAD

**Issue by Josephasafg** [tmotagam/Secweb#2]
I'm Trying to open a PR regarding a fix in the CSP `__PolicyCheck__` function. 
In that function you check `if not keys.index('style-src')` which is an issue in case `style-src`  or `script-src` is in index 0.
I think it would be better to change this condition to `if keys.index('style-src') is None`

**Comment by tmotagam** [comment]
You have to first fork the repo then commit in the forked repo and then you can open a pull request.
