### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by damvolkov** [tmotagam/Secweb#3]
Hey man!

Im using you amz library for a fastapi app, but, all middlewares that are in place (all of them that has dispatch methods) at the startup of the app, within certain period raise this error:

![image](https://user-images.githubusercontent.com/58026317/177139034-5998ba2f-7be2-4463-b4af-3c21400ff2be.png)

Getting deeper on your code I noticed that, 

![image](https://user-images.githubusercontent.com/58026317/177139705-892e00ba-7990-4047-bd6a-0b5e49bbac80.png)

Here in base.py, this stream RuntimeError is raised sooner or later with all dispatch middlewares. How should we solve this using your middlewares and not having to use an specific error handler to that?

Thanks in advance

**Comment by damvolkov** [comment]
Seems that is related to this issue:

https://stackoverflow.com/questions/71222144/runtimeerror-no-response-returned-in-fastapi-when-refresh-request

**Comment by tmotagam** [comment]
Hey @TatanParker ,
 Thanks for pointing out the bug. I was able to reproduce the bug from the link you gave me I will be working on the workaround and release the patch.

**Comment by damvolkov** [comment]
Nice, friend.

My suggestions is manipulating the HttpBaseMiddleware like :

```
class SecureBaseMiddleware(BaseHTTPMiddleware):
    async def __call__(self, scope, receive, send) -> None:
        request = Request(scope, receive, send)
        try:
            await super().__call__(scope, receive, send)
        except RuntimeError as e:
            if not await request.is_disconnected():
                raise e
            return

    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        raise NotImplementedError()
```

If you want me to do it I can do it.

https://github.com/encode/starlette/discussions/1527#discussioncomment-2234702

**Comment by tmotagam** [comment]
[SuppressMiddleware-1.0.0-py3-none-any.zip](https://github.com/tmotagam/Secweb/files/9357066/SuppressMiddleware-1.0.0-py3-none-any.zip)
Hey @TatanParker ,
This is the patch of the bug you mentioned you have to activate this middleware in the end of all the middleware's to catch that bug and avoid the runtime error.
 Thanks.
