### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by nikhilsarma** [tmotagam/Secweb#4]
We just upgraded to Secweb 1.7.1 and faced with this syntax issue. [syntax introduced in python 3.10]

things work fine in Secweb 1.6.0 though.

`File "/usr/local/lib/python3.9/site-packages/Secweb/StrictTransportSecurity/StrictTransportSecurityMiddleware.py", line 19, in HSTS
def __init__(self, app: ASGIApp, Option: dict[str, int | bool] = {'max-age': 432000, 'includeSubDomains': True, 'preload': False}):
TypeError: unsupported operand type(s) for |: 'type' and 'type'`

**Operating System**
Linux

**Secweb Version**
1.7.1

**Python Version**
Python 3.9

**Comment by tmotagam** [comment]
Hi @nikhilsarma,
 You can use the new version 1.7.2.
 Thanks for your feedback.

**Comment by nikhilsarma** [comment]
Things are good now.. Thanks for the quick turnback.
