### ISSUE TITLE
Add Permissions-Policy middleware

### ISSUE THREAD

**Issue by IlyaKalosha1** [tmotagam/Secweb#7]
This policy is becoming more and more required by several security checkers(example https://securityheaders.com/)
Would you mind adding this additional middleware to the list of existing?
MDN https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy

**Comment by IlyaKalosha1** [comment]
I already have ready PR for this, pls add me as a contributor so I can PR

**Comment by tmotagam** [comment]
Hi @IlyaKalosha1,
 I already have the permission policy header implemented in the dev branch and also a wheel of the dev branch in the release section please check it out.

**Comment by IlyaKalosha1** [comment]
Great news, thank you.
When is it going to be released as latest version?
Also you can close this issue when it's released

**Comment by roma-ash** [comment]
@tmotagam hey! 
Any ideas when permission policy middleware will be in a main branch?

**Comment by tmotagam** [comment]
@roma-ash hi
The middleware will be in the main branch once it gets out of the draft stage.
